// AUTO-GENERATED by scripts/gen-teleport-ids.mjs — do not edit by hand.
// Maps OSRS item id -> our teleport id (every charge/variant maps to the same id,
// so owning ANY counts). Source: osrsreboxed items dump (untradeables + variants).

export const TELEPORT_ITEM_IDS = {
  // skillsNecklace: Skills necklace(4), Skills necklace(3), Skills necklace(2), Skills necklace(1), Skills necklace, Skills necklace(6), Skills necklace(5)
  11105: "skillsNecklace", 11107: "skillsNecklace", 11109: "skillsNecklace", 11111: "skillsNecklace", 11113: "skillsNecklace", 11968: "skillsNecklace", 11970: "skillsNecklace",
  // combatBracelet: Combat bracelet(4), Combat bracelet(3), Combat bracelet(2), Combat bracelet(1), Combat bracelet, Combat bracelet(6), Combat bracelet(5)
  11118: "combatBracelet", 11120: "combatBracelet", 11122: "combatBracelet", 11124: "combatBracelet", 11126: "combatBracelet", 11972: "combatBracelet", 11974: "combatBracelet",
  // gamesNecklace: Games necklace(8), Games necklace(7), Games necklace(6), Games necklace(5), Games necklace(4), Games necklace(3), Games necklace(2), Games necklace(1)
  3853: "gamesNecklace", 3855: "gamesNecklace", 3857: "gamesNecklace", 3859: "gamesNecklace", 3861: "gamesNecklace", 3863: "gamesNecklace", 3865: "gamesNecklace", 3867: "gamesNecklace",
  // ringOfWealth: Ring of wealth, Ring of wealth (5), Ring of wealth (4), Ring of wealth (3), Ring of wealth (2), Ring of wealth (1), Ring of wealth scroll, Ring of wealth (i), Ring of wealth (i5), Ring of wealth (i4), Ring of wealth (i3), Ring of wealth (i2), Ring of wealth (i1)
  2572: "ringOfWealth", 11980: "ringOfWealth", 11982: "ringOfWealth", 11984: "ringOfWealth", 11986: "ringOfWealth", 11988: "ringOfWealth", 12783: "ringOfWealth", 12785: "ringOfWealth", 20786: "ringOfWealth", 20787: "ringOfWealth", 20788: "ringOfWealth", 20789: "ringOfWealth", 20790: "ringOfWealth",
  // amuletOfGlory: Amulet of glory, Amulet of glory(1), Amulet of glory(2), Amulet of glory(3), Amulet of glory(4), Amulet of glory, Amulet of glory (t4), Amulet of glory (t3), Amulet of glory (t2), Amulet of glory (t1), Amulet of glory (t), Amulet of glory (t6), Amulet of glory (t5), Amulet of glory(5), Amulet of glory(6), Amulet of eternal glory, Amulet of glory
  1704: "amuletOfGlory", 1706: "amuletOfGlory", 1708: "amuletOfGlory", 1710: "amuletOfGlory", 1712: "amuletOfGlory", 8283: "amuletOfGlory", 10354: "amuletOfGlory", 10356: "amuletOfGlory", 10358: "amuletOfGlory", 10360: "amuletOfGlory", 10362: "amuletOfGlory", 11964: "amuletOfGlory", 11966: "amuletOfGlory", 11976: "amuletOfGlory", 11978: "amuletOfGlory", 19707: "amuletOfGlory", 20586: "amuletOfGlory",
  // necklaceOfPassage: Necklace of passage(5), Necklace of passage(4), Necklace of passage(3), Necklace of passage(2), Necklace of passage(1)
  21146: "necklaceOfPassage", 21149: "necklaceOfPassage", 21151: "necklaceOfPassage", 21153: "necklaceOfPassage", 21155: "necklaceOfPassage",
  // slayerRing: Slayer ring (8), Slayer ring (7), Slayer ring (6), Slayer ring (5), Slayer ring (4), Slayer ring (3), Slayer ring (2), Slayer ring (1), Slayer ring (eternal)
  11866: "slayerRing", 11867: "slayerRing", 11868: "slayerRing", 11869: "slayerRing", 11870: "slayerRing", 11871: "slayerRing", 11872: "slayerRing", 11873: "slayerRing", 21268: "slayerRing",
  // ringOfDueling: Ring of dueling(8), Ring of dueling(7), Ring of dueling(6), Ring of dueling(5), Ring of dueling(4), Ring of dueling(3), Ring of dueling(2), Ring of dueling(1)
  2552: "ringOfDueling", 2554: "ringOfDueling", 2556: "ringOfDueling", 2558: "ringOfDueling", 2560: "ringOfDueling", 2562: "ringOfDueling", 2564: "ringOfDueling", 2566: "ringOfDueling",
  // ringOfElements: Ring of the elements, Ring of the elements
  26815: "ringOfElements", 26818: "ringOfElements",
  // xericTalisman: Xeric's talisman (inert), Xeric's talisman
  13392: "xericTalisman", 13393: "xericTalisman",
  // royalSeedPod: Royal seed pod
  19564: "royalSeedPod",
  // teleportCrystal: Teleport crystal (4), Teleport crystal (3), Teleport crystal (2), Teleport crystal (1), Crystal teleport seed, Teleport crystal (5), Teleport crystal, Enhanced crystal teleport seed
  6099: "teleportCrystal", 6100: "teleportCrystal", 6101: "teleportCrystal", 6102: "teleportCrystal", 6103: "teleportCrystal", 13102: "teleportCrystal", 23904: "teleportCrystal", 23959: "teleportCrystal",
  // stonyBasalt: Stony basalt
  22601: "stonyBasalt",
  // icyBasalt: Icy basalt
  22599: "icyBasalt",
  // quetzalWhistle: Basic quetzal whistle blueprint, Enhanced quetzal whistle blueprint, Perfected quetzal whistle blueprint, Torn enhanced quetzal whistle blueprint, Torn perfected quetzal whistle blueprint, Basic quetzal whistle, Enhanced quetzal whistle, Perfected quetzal whistle
  29251: "quetzalWhistle", 29253: "quetzalWhistle", 29256: "quetzalWhistle", 29259: "quetzalWhistle", 29261: "quetzalWhistle", 29271: "quetzalWhistle", 29273: "quetzalWhistle", 29275: "quetzalWhistle",
  // digsitePendant: Digsite pendant (1), Digsite pendant (2), Digsite pendant (3), Digsite pendant (4), Digsite pendant (5)
  11190: "digsitePendant", 11191: "digsitePendant", 11192: "digsitePendant", 11193: "digsitePendant", 11194: "digsitePendant",
  // kharedstsMemoirs: Kharedst's memoirs, Book of the dead
  21760: "kharedstsMemoirs", 25818: "kharedstsMemoirs",
  // pendantOfAtes: Pendant of ates (inert), Pendant of ates
  29892: "pendantOfAtes", 29893: "pendantOfAtes",
  // questPointCape: Quest point cape, Quest point cape (t)
  9813: "questPointCape", 13068: "questPointCape",
  // ectophial: Ectophial, Ectophial
  4251: "ectophial", 4252: "ectophial",
  // farmingCape: Farming cape, Farming cape(t)
  9810: "farmingCape", 9811: "farmingCape",
};

// Pure. arrays = flat [id,qty,id,qty,...] (bank, inventory, equipment, rune_pouch,
// seed_vault). Returns a Set of our teleport ids present with qty>0. Never throws.
export function ownedTeleportIdsFromItems(...arrays) {
  const owned = new Set();
  for (const arr of arrays) {
    if (!Array.isArray(arr)) continue;
    for (let i = 0; i + 1 < arr.length; i += 2) {
      const id = Number(arr[i]);
      const qty = Number(arr[i + 1]);
      if (!Number.isFinite(id) || !Number.isFinite(qty) || qty <= 0) continue;
      const tp = TELEPORT_ITEM_IDS[id];
      if (tp) owned.add(tp);
    }
  }
  return owned;
}
